apiVersion: v1
kind: Service

metadata:
  name: eureka-server
  labels:
    app: eureka-server

spec:
  type: {{ .Values.service.type }}

  selector:
    app: eureka-server

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
